#include <wx/wx.h>
#include <wx/taskbar.h>
#include <wx/notifmsg.h>
#include <windows.h>
#include <fstream>
#include <string>
#include <thread>
#include <cwctype>
#include <cctype>
#include <wctype.h>